<template>
<Login />
</template>

<script>
import Login from './components/Login.vue'

export default {
  name: 'App',
  components: {Login}
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}

html,
body {
  padding: 0;
  margin: 0;
  background: #fafafa;
}

* {
  box-sizing: border-box;
}

:root {

  --text-color: #5d9b49;
  --speed: 500ms; 
}

/* mini reset */
body{
  margin: 0;
  background: #fafafa;
}
body,h1,h2,p,a,input{
  color: #555;
  font-family: Consolas, Arial;
  text-decoration: none;
  font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen,
    Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;
}

.flex_row {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    align-items: center;
}

.flex_col {
    display: flex;
    flex-wrap: wrap;
    flex-direction: column;
    justify-content: center;
    align-items: center;
}

.rm_margin > p {
    margin: 0;
}


.login_wrapper {
    width: 100%;
    height: 100vh;
    -webkit-animation: fade-in 1.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
	        animation: fade-in 1.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;



}

input:focus {
    outline: none;
}

.background_gradient {
    padding: 0.2%;
    width: 30%;
    height: fit-content;
    background-color: #fff;
    border-radius: 10px;
    border-radius: 15px;
    background: linear-gradient(to bottom, #3eff00f0, #081ac1b5);
    box-shadow: #3eff00f0 0px 4px 12px;
}


.login_container {
    width: 100%;
    padding: 15% 0;
    height: 100%;
    border-radius: 10px;
    background-color: #fff;
}

.login_image{
    width: 60%;
    margin: 0 auto;
    padding: 4%;
}

.login_image > img {
    width: 100%;
}

.login_message > p {
    font-size: 20px;
}

.login_form {
    width: 80%;
}
.login_form > form {
    width: 100%;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
}

.input_wrap {
    width: 100%;
    display: flex;
    justify-content: flex-start;
    align-items: center;
    position: relative;
    z-index: 0;
}

.input_wrap > img{
    z-index: 1;
    padding: 0.5%;
    margin-left: 2.5%;
    width: 5%;
    position: absolute;
    object-fit: cover;
}

.input_wrap > input[type="password"] {
    z-index: 0;
    padding: 3%;
    padding-left: 8%;
    border-width: 1px;
    border-color: #80819445;
    border-style: solid;
    width: 100%;
    height: 40px;
    margin: 4% 0;
 }
 .input_wrap > input[type="email"] {
    z-index: 0;
    padding: 3%;
    padding-left: 8%;
    border-width: 1px;
    border-color: #80819445;
    border-style: solid;
    width: 100%;
    height: 40px;
    margin: 4% 0;
 }
 .input_wrap > input[type="password"]:focus {
    border: 2px solid #3eff00f0;
    border-radius: 25px;
    border-image-source: linear-gradient( #3eff00f0, #237507f0);
    border-image-slice: 1;
}
.input_wrap > input[type="email"]:focus {
    border: 2px solid #3eff00f0;
    border-radius: 25px;
    border-image-source: linear-gradient( #3eff00f0, #237507f0);
    border-image-slice: 1;
}
 .bold > p{
    font-weight: 500;
    margin: 5px 0;
    text-align: center;
 }

 .forgot_password > p {
     color: var(--text-color);
 }

 .submit_button {
     width: 100%;
     margin-top: 4%;
     padding: 2.5%;
     border-radius: 35px;
     box-shadow: #8dfa6a 2px 5px 3px;
     background-color: var(--text-color);
 }

 .submit_button > p{
    text-align: center;
    color: #fff;
    font-size: 18px;
}

.authentication_message > p {
    font-size: x-small;
    color: red;
}

.auth > form > input[type="text"] {
    margin-bottom: 0;
}

.message_check {
    padding: 6% 0;
}

.message_check > input[type="checkbox"]{
    width: 14px;
    height: 14px;
}

.code_question > p:last-child {
    color: var(--text-color);
}

.random_questions {
    width: 100%;
}

.random_questions > input[type="text"] {
    width: 100%;
    padding: 2.5%;
    border-radius: 4px;
    border-width: 1px;
    border-color: #80819445;
    border-style: solid;
}

.random_questions > p{
    text-align: left;
}




@media (max-width: 768px) and (min-width: 60px) { 
    .background_gradient {
        width: 80%;
        height: fit-content;
    } 
    
    .message_check > p {
        font-size: 12px;
    }
 }

/* ----------------------------------------------
 * Generated by Animista on 2022-3-9 19:10:28
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in
 * ----------------------------------------
 */
@-webkit-keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
@keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}




</style>
